### ISSUE TITLE
Note about sinkhole

### ISSUE THREAD

**Issue by richleland** [sanchothefat/sparkpost-wp-mail#1]
Hey @sanchothefat thanks for releasing this! I wanted to note that if people want to send test messages without using the sandbox, we have a sinkhole that will discard them. They count against your total send but with 100k free, it's totally fine to send tests using it. Here's our support article about it:

https://support.sparkpost.com/customer/en/portal/articles/2361300-how-to-test-integrations

Totally get if folks don't want to set up the domain initially, but it really will provide a better experience than the sandbox.

Also - we'd welcome any contributions to our wordpress plugin:
https://github.com/SparkPost/wordpress-sparkpost/

Thanks again!

**Comment by roborourke** [comment]
Cool! Thanks Richard.

That's good to know re the sinkhole, very useful :)

I did check out the plugin too, looks solid. I put this together as it
suits the work we do at Human Made where a lot of this stuff is provisioned
and configured on the fly.

## 

Robert O'Rourke
_mobile:_ +447816329424
_skype: *rob.o.rourke
*web:_ röb.co

**Comment by richleland** [comment]
Cool - well let us know if there's anything we can help with. We're hanging out on http://slack.sparkpost.com if you want to chat.

**Comment by asherber** [comment]
In case anyone finds their way here, the article about the SparkPost sinkhole domain is now here: https://support.sparkpost.com/customer/en/portal/articles/2560839-how-do-i-test-using-the-sink-server-on-sparkpost-?b_id=7411
